<?php
/** @var \Magento\Customer\Block\Account\AuthenticationPopup $block */

$viewFileUrl = $block->getViewFileUrl('images/loader-1.gif');
$escapedViewFileUrl = $block->escapeJs(
    $block->escapeUrl(
        $viewFileUrl
    )
);
?>
<div id="signInPopup" data-bind="scope:'signInPopup'"
     style="display: none;">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#signInPopup": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?= $escapedViewFileUrl ?>"
            }
        }
    </script>
</div>
